# language 语言
language: zh-CN

# name 名称
name: Lete乐特

# 自定义页脚字体颜色
footer_color: '#000 '
footer_a_color: '#000'
# 鼠标移动到超链接上显示的颜色
a_hover: '#e58a8a'
# 自定义名称颜色
name_color: '#80bdab'
#自定义描述字体颜色
desc_color: '#000'

# 自定义背景
# bg_img: url(https://cdn.jsdelivr.net/gh/lete114/CDN2/img/wei_er_li_te/3.jpg)
# bg_img: '#fff'
# bg_img: 'white'
bg_img: '#fff'
# 开站年份
Copyright: 2019

#关键字
keywords: Lete乐特,Java,JavaWeb,Java常用框架,Spring,SpringBoot,SpringMVC,MyBatis,数据库,MySQL,C#,.NET,开发工具,Git,GitHub,Gitee,(My)Eclipse,IDEA, Hexo,Linux,Maven,前端基础知识,HTML,CSS,JavaScript,jQuery,Ajax,Bootstrap,工具&#x2F;资源,教程,分享,推荐,娱乐,摄影,C#,CMD,Developer,Programmer,Coder

# logo
logo: Lete乐特 's Blog
logo_link: https://blog.lete114.top

# favicon 图标
favicon: /image/favicon.ico

# avatar 头像
avatar: /image/avatar.png

# site description 网站描述
description: 我相信我可以，但我一直在路上，所以我有无限的可能！！

# 个人描述
desc: 我相信我可以，但我一直在路上，所以我有无限的可能！！<br>人生只有一次，大胆的生活，怎么舒服怎么来！！

# menus 菜单
menus:
  MengD: https://github.com/lete114/hexo-theme-MengD
#  YiliaBlog: https://yilia.lete114.top/
#  MUSIC: https://music.lete114.top/
#  NavSite: https://nav.lete114.top/
#  Links: https://blog.lete114.top/link/
#  about:  https://blog.lete114.top/about/


# 自定义图标
iconfont: https://cdn.jsdelivr.net/gh/sviptzk/StaticFile_HEXO@master/butterfly/css/iconfont.min.css
fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css
# Icon 图标
links:
  iconfont icon-youxiang: mailto:lete@lete114.top
  iconfont icon-github3: https://github.com/lete114
  iconfont icon-csdn: https://me.csdn.net/Lott0419
  iconfont icon-zhihu: https://www.zhihu.com/people/lete114


ICP:
  enable: false
  icon: https://cdn.jsdelivr.net/gh/lete114/lete114.github.io/img/icp.png
  url: 
  text: 